name: First Workflow

on: [push]

jobs:
  actions_demo:
    runs-on: ubuntu-latest
  
    steps:
    - run: echo "Hello World!"
    - run: touch FileMadeByWorkflow.txt
    - run: echo "this is some text on the file" >> FileMadeByWorkFlow.txt
    - run: cat FileMadeByWorkFlow.txt
    - run: ls -a
    - run: whoami
    - run: git clone https://github.com/nparojcic/Nov_22_Git_Demo
    
  better_action:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - run: chmod +x cool_script.sh # granting permission access to our script 
    - run: ./cool_script.sh # running the script

  env_vars_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello world