name: First Workflow

on: [push]

jobs:
  actions_demo:
    runs-on: ubuntu-latest
  
    steps:
    - run: echo "Hello World!"
    - run: touch FileMadeByWorkflow.txt
    - run: echo "this is some text on the file" >> FileMadeByWorkFlow.txt
    - run: echo .
    - run: whoami
