name: First Workflow

on: [push]

jobs:
  actions_demo:
    runs-on: ubuntu-latest
  
    steps:
    - run: sleep 10
    - run: echo "Hello World!"
    - run: touch FileMadeByWorkflow.txt
    - run: echo "this is some text on the file" >> FileMadeByWorkFlow.txt
    - run: cat FileMadeByWorkflow.txt
    - run: ls -a
    - run: whoami
   
